### ISSUE TITLE
Error when attempting to bulk import hosts

### ISSUE THREAD

**Issue by ghost** [vatesfr/xo-import-servers-csv#8]
Encountering the below errors for each host when running - 
`xo-import-servers-csv 'http://10.0.10.105' username password < /tmp/servers.csv`

`  { host: undefined,
    error:
     { JsonRpcError: invalid parameters
         at Peer._callee$ (/usr/local/lib/node_modules/xo-import-servers-csv/node_modules/json-rpc-peer/dist/index.js:245:17)
         at tryCatch (/usr/local/lib/node_modules/xo-import-servers-csv/node_modules/regenerator-runtime/runtime.js:62:40)
         at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/xo-import-servers-csv/node_modules/regenerator-runtime/runtime.js:296:22)
         at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/xo-import-servers-csv/node_modules/regenerator-runtime/runtime.js:114:21)
         at step (/usr/local/lib/node_modules/xo-import-servers-csv/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
         at /usr/local/lib/node_modules/xo-import-servers-csv/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
         at Promise.F (/usr/local/lib/node_modules/xo-import-servers-csv/node_modules/core-js/library/modules/_export.js:36:28)
         at Peer.<anonymous> (/usr/local/lib/node_modules/xo-import-servers-csv/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
         at Peer.exec (/usr/local/lib/node_modules/xo-import-servers-csv/node_modules/json-rpc-peer/dist/index.js:289:21)
         at Peer._write (/usr/local/lib/node_modules/xo-import-servers-csv/node_modules/json-rpc-peer/dist/index.js:175:12) code: 10, data: [Object] } },`

$ cat /tmp/servers.csv
10.11.19.201,root,password
10.11.19.202,root,password
10.11.19.203,root,password

Any tips? Thanks!

**Comment by julien-f** [comment]
You need to add headers to your columns, check out the example in the README :-)

**Comment by ghost** [comment]
@julien-f  Derp.. thanks much, your work saved me hours.
